### ISSUE TITLE
"Email" name in menu is confusing

### ISSUE THREAD

**Issue by roumano** [ltb-project/self-service-password#111]
Hi,

We use the ssp to permit user to manage their password.

We got feedback from many users (non technical user) don't understand what it's the "Email" (or Mail in French) function.
They think it's use to change their email address so they never click & use it ...

Maybe a better name (like Reset by mail ? ) 
And/or a Popover to describe it ?

**Comment by coudot** [comment]
We can indeed propose some popovers to describe tabs.

To override tab label, you can set this in your config.inc.php:
````php
$messages['menutoken'] = "Reset by mail";
````

**Comment by plewin** [comment]
: *
`"conf/$lang.inc.php"`
not 
`config.inc.php`
and it is not in v1.0

overrides of messages with config.inc.php is not supported in v1.0

In v1.0 one must edit lang/$lang.inc.php

**Comment by coudot** [comment]
Not true, in 1.0 you can override messages in config.inc.php like we do for questions: https://ltb-project.org/documentation/self-service-password/latest/config_questions#edit_questions

The only limitation is that this is a global override for all languages.

In 1.1 we will indeed be able to create custom lang files to override messages for different languages.

**Comment by plewin** [comment]
In fact not, it looks like it is possible in 1.0 but it is not.

With `config.inc.php` it is only possible to define messages that are not already defined in the language files e.g. from the sample config file `$messages['questions']['ice']`.

Messages that are defined cannot be overriden by `config.inc.php`. It is because of the order of the includes in `index.php`.

First `config.inc.php` is included.
https://github.com/ltb-project/self-service-password/blob/v1.0/index.php#L25
Then SSP guess the language to load.
Then it includes `"lang/$lang.inc.php"`
https://github.com/ltb-project/self-service-password/blob/v1.0/index.php#L47

Hence `lang/$lang.inc.php` overrides variables from config.inc.php and not the opposite way.

`$messages['menutoken']` is defined in `"lang/$lang.inc.php"`, defining it in `config.inc.php` will not be useful.

**Comment by coudot** [comment]
@plewin you are right, sorry.
