### ISSUE TITLE
Use password modify extended operation

### ISSUE THREAD

**Issue by coudot** [ltb-project/self-service-password#155]
In PHP 7.2 we will be able to use password modify extended operation. We need to add an option to be able to use it (and test if the function is available).

**Comment by plewin** [comment]
I tried the functions on a php 7.2.1 / apache directory server 2.0.0-M24 on windows

ldap_exop_password did not work because of some "Decoding error"
https://gist.github.com/plewin/3ecfcacb2d7846d28598859f90919898#file-trace-log-L54

ldap_exop with LDAP_EXOP_MODIFY_PASSWD worked but when the password cannot be modified because of password policy, ldap_exop said it was still a success. It is not possible to know in php if the password was really changed or not, nor getting the details of the problem without using ldap_get_option with LDAP_OPT_DIAGNOSTIC_MESSAGE
https://gist.github.com/plewin/3ecfcacb2d7846d28598859f90919898#file-trace-log-L91
https://gist.github.com/plewin/3ecfcacb2d7846d28598859f90919898#file-trace-log-L98

**Comment by bilbo-the-hobbit** [comment]
hello,

if you have issues with php 7.x an php ldap you can ask the developper directly @MCMic

Cheers

**Comment by MCMic** [comment]
@plewin Hello, can you please open tickets on https://bugs.php.net/ about these problems?
EXOP support code is quite new and might indeed need a few fixes in the PHP versions to come.
