### ISSUE TITLE
Self-service also for local system passwords stored in /etc/shadow

### ISSUE THREAD

**Issue by AvtechScientific** [ltb-project/self-service-password#160]
It would be nice to have self-service also for local system passwords stored in /etc/shadow. Is it currently possible or not? Are you aware of any good WEB UI to change/reset local system passwords?

Thank you!

**Comment by plewin** [comment]
Hi,

It is not possible currently to use LTB SSP to change local password from /etc/passwd / shadow because this tool is tied with ldap code.
There is a work in progress https://github.com/ltb-project/self-service-password/pull/158 (basically a big  refactor of the code) that would permit to use this tool with almost anything you want e.g. .htpasswd, databases or /etc/password instead of the ldap server with minimum modifications. But impossible to tell you if it will be merged and if it is, when.

If i remember correctly Webmin can do what you want but I am not sure and it's been a while since the last time i used it. I think it is overkill for just this usage but perhaps it will suit you. Possibly alternative webpanels configured with minimal rights should offer you this feature.

**Comment by coudot** [comment]
Hello @AvtechScientific, using a web interface to change a local account seems not a good idea. It means your web server will have root access to edit /etc/shadow, which is very dangerous.

If a user needs to change a password on a local system, he logs in and run 'passwd' in command line.

The best for you is to configure an LDAP directory and connect your servers to this directory to have a central password for all your servers.

**Comment by AvtechScientific** [comment]
Hello @coudot ,

> It means your web server will have root access to edit /etc/shadow, which is very dangerous.
Yes but only in one place and everybody does it. The code needs indeed to be bullet-proof.

> If a user needs to change a password on a local system, he logs in and run 'passwd' in command line.
It is meant for not so technically savvy users. It is also relevant for SFTP only accounts.

> The best for you is to configure an LDAP directory and connect your servers to this directory to have a central password for all your servers.
We prefer to have a decentralized infrastructure in our use case in order to avoid a single point of failure.

**Comment by hollaho** [comment]
> The code needs indeed to be bullet-proof.
Well, such a thing does not exist, especially if code gets complicated by trying to do too much, this is always a trade-off.

> It is also relevant for SFTP only accounts.
Which can be solved with ldap just as well. Indeed this comes down to whether one wants a centralized or decentralized setup. ldap allows both, but it is unnecessarily complicated for a decentralized approach.

**Comment by r2evans** [comment]
@AvtechScientific  yes, bullet-proof it would have to be. But I think an "LDAP tool" is the wrong place to add "local user modifications". The fact that it is intended for not-so-technically savvy users does not justify the complexity and potential for security issues that this presents.

How do you intend to tie *"decentralized infrastructure"* with a tool that only changes local accounts? I thought the decentralized nature of LDAP was for exactly that purpose.

**Comment by coudot** [comment]
I close this issue as we won't allow local user password modification
