### ISSUE TITLE
SSH key add - prepend a string - possible new feature

### ISSUE THREAD

**Issue by eperry** [ltb-project/self-service-password#168]
Looking for comments:

I was thinking that for the SSH  key upload, it would be nice to "prepend" some options to the public key

I guess we could just add a static string in the config file that prepends the information to all keys. 

An	example	authorized_keys	file:
	# Comments allowed at start of line
	**from="*.sales.example.net,!pc.sales.example.net"**  ssh-rsa	AAAAB2...19Q==  john@example.net

The benefit of this is you can add a little more security around the user by default. Like Restricting them to all internal networks  from="192.168.0.0/16,10.0.0.0/8, ......"   and maybe disable tunneling or what not. by default. 

so before I looked at making the change, I thought I would double check if anyone had any other idea's or has tried it.

**Comment by bilbo-the-hobbit** [comment]
Le 04/12/2017 à 14:47, Edward Perry a écrit :
> I was thinking that for the SSH key upload, it would be nice to
> "prepend" some options to the public key
> 
> I guess we could just add a static string in the config file that
> prepends the information to all keys.
> 
> An example authorized_keys file:
> # Comments allowed at start of line
> *from="*.sales.example.net,!pc.sales.example.net"* ssh-rsa
> AAAAB2...19Q== john@example.net <mailto:john@example.net>
> 
> The benefit of this is you can add a little more security around the
> user by default. Like Restricting them to all internal networks
> from="192.168.0.0/16,10.0.0.0/8, ......" and maybe disable tunneling or
> what not. by default.

hello,

this is not a good idea to add such stuff into ssh key, been there, done
that :)

you can use pam authz to do fine delegation of very people can connect

Cheers
-- 
Benoit Mortier
CEO
OpenSides "logiciels libres pour entreprises" : http://www.opensides.eu/
Promouvoir et défendre le Logiciel Libre http://www.april.org/
Main developer in FusionDirectory : http://www.fusiondirectory.org/
Official French representative for OPSI : http://opsi.org/

**Comment by eperry** [comment]
Can you provide some details on why it is not a good idea?  Did you run into issues or was it more just preference?

**Comment by plewin** [comment]
I would recommend against it, you will need to check if the public key is already prepended each time and validate the user input as some options can be cancelled. I believe it is easy to make something works but really really hard to make it right, secure, and handling all cases. Computing and validating public keys is painfull.
Also what if you need to change the "from" options ?

**Comment by bilbo-the-hobbit** [comment]
hello,

from a security point of view it had nothing of value. Managing correctly all the option of an ssh key is difficult to do securely, i have done that in the past and it was cumbersone and didn't give more security. you better do the control at the server side with pam to block user not allowed at all or/and remove options directly at the ssh server.

Cheers

**Comment by eperry** [comment]
@plewin  no you do not need to validate the public key , anyway were are not doing it now. But your right additional logic would have to be added to parse the input string and allow updates.  As for changing the value yes you would have to either update the string manually or write a script 

@bilbo-the-hobbit . I don't necessarily have access to the machines/vm's/dockers they spawn up, but I do have authority over their passwords and ssh keys if they use central authentication.

**Comment by bilbo-the-hobbit** [comment]
hello,

you where talking about an authorized_keys file that had me thinking you have access to the box ? if they have access to their public key they can change it themselves. 

i don't see how you can enforce that user side.

**Comment by edperry** [comment]
@bilbo-the-hobbit   yes we are talking the authorized_keys (public key) which is managed by SSP  and allows users to update their public keys.

I was trying to see what the opinion of allowing a static varible to append "options"  to the public string at the administration level. This example would allow allow this public key to be used from the 10 network or 172.26 network

**from="10.X.X.X,172.26.X.X"** ssh-rsa	AAAAB2...19Q== john@example.net

Though other options could be added like disabling tunneling, preventing shell or other ssh features.

My idea is to prepend the "RFC-1918" non-rotatable networks so that users can't get accessed from the internet when using these id's.  Of course if they create local accounts I can not prevent that but that is a different issue.

but at @plewin point, if I go this way, data will have to be validated, and a way of updating the data might have to be added as well.   So it is not just a simple prepend of a string, there has to be some syntax checking at minimum.

**Comment by plewin** [comment]
Thank you for this ideas, I am closing this issue because the question was answered.
