### ISSUE TITLE
Reset questions and answers (Questions/suggestion?)

### ISSUE THREAD

**Issue by BShadeWork** [ltb-project/self-service-password#183]
I may have missed this in docs (in which case, apologies), but noticed a couple of things around the reset using questions (All low priority if changes needed)

- There is just one question - Would be good to have more than one to be answered (configurable say 1-3 questions) ?
- The answer seems to be in clear text in the ldap 'info' field. Probably me not having the right knowledge here, but can this be hashed so not clear text?
- Would also suggest all the questions are in config (default question moved into config as well as extra ones) so they can be changed more easily and not use the 'default' questions (Birthday etc)? 

Thoughts?

**Comment by plewin** [comment]
Hi,

There is room for improvements in the reset by security questions feature.

> Would be good to have more than one to be answered (configurable say 1-3 questions) ?

Yes it would be good to have more than one question supported. This is not currently supported and there is a lot of thinking to do to implement multiple security questions. Eg. Multi attributes, multi values for one attribute, pack the values in one attribute value... How to configure how many answers must be provided...

> The answer seems to be in clear text in the ldap 'info' field. [...] Can this be hashed so not clear text?

This is not supported but I guess it should. It is actually trivial to implement this (at least for an unsalted, potentially with pepper) if you do not care about migration of questions/answers that are not hashed (answer not hashed won't work anymore).
I would like to add that there is another thing that can be done, it would be to use ldap_compare to compare the answer on the directory server instead of ssp. With this, one could configure ACL so the "info" attribute is only writeable and comparable. The problem with that is that we may need an other field to store the question in a second attribute since the other attribute is not readable.

> Would also suggest all the questions are in config (default question moved into config as well as extra ones) so they can be changed more easily and not use the 'default' questions (Birthday etc)?

Oh. I never noticed this. Yes, it is not convenient if you do not want to use the default questions, you will have to remove them from each language file. But I disagree with moving them to the config file because they need to be translated. I guess the best way to prevent this problem would be to add an $allowedQuestions = ['birthday', 'ice'] config to only display the questions you want to use and not all the available translations. This is convenient for us as we will be able to provide many more translated questions to choose for our users.

**Comment by BShadeWork** [comment]
Thanks. Can't disagree with anything you have said 👍

**Comment by coudot** [comment]
I will work on the answer encryption very soon, we need to prepare a script that can encrypt clear text values to ease migration. I will open a new issue so we can work separately on each items.

**Comment by shawnmckinney** [comment]
Hello, we have a project that needs to support multiple questions on password reset. It looks like this hasn't been implemented yet. Is this true?  If no, would be interested in helping to work on the solution.

**Comment by coudot** [comment]
Hello @shawnmckinney !

Indeed, this is not yet implemented, but we could indeed work on it together!

**Comment by shawnmckinney** [comment]
Hey Clement, very nice to hear. I've been thinking about how it can be done. Seems like it would need to be a multivalued attribute configured in much the same way as the single.  Each value would be an index and the answer to the question separated by a configurable delimiter.

For example:
# Answer attribute should be hidden to users!
$answer_objectClass = "extensibleObject";
$answer_attribute = "answers";

# 
$messages['1'] = "Favorite Ice Cream";
$messages['2'] = "First Concert";
$messages['3'] = "Favorite Programming Language";


dn: uid=smckinney,ou=People,dc=example,dc=com
objectClass: extensibleObject
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
cn: shawn mckinney
sn: mckinney
answers: 1$Chocolate Chip
answers: 2$Beatles
answers: 3$COBOL
mail: smckinney@example.com
uid: smckinney
userPassword: ...

*** 

does this seem reasonable?  Of course we'd need to preserve the encryption of the answers.

**Comment by coudot** [comment]
In fact we have two options:
* the first is the one you propose, that is to have a mutlivaluated attribute. For the separator, I would have used `{}`, for example:`{ice}vanilla`
* the other one is to serialize all answers in JSON and put this in a single valued attribute

I don't have any preference for the moment.

The hard work is to adapt the screen where a user can save its answer. Then we need to know if we allow to ask several questions to reset the password (for example you need to answer at least 2 questions) or if only one answer will be asked, like today.

**Comment by shawnmckinney** [comment]
> On May 9, 2019, at 11:11 AM, Clément OUDOT <notifications@github.com> wrote:
> 
> In fact we have two options:
> 
> 	• the first is the one you propose, that is to have a mutlivaluated attribute. For the separator, I would have used {}, for example:{ice}vanilla
> 	• the other one is to serialize all answers in JSON and put this in a single valued attribute
> I don't have any preference for the moment.

If there are no objections I’ll aim for the first option.

> 
> On May 9, 2019, at 11:11 AM, Clément OUDOT <notifications@github.com> wrote:
> 
> The hard work is to adapt the screen where a user can save its answer. Then we need to know if we allow to ask several questions to reset the password (for example you need to answer at least 2 questions) or if only one answer will be asked, like today.

Makes sense. Probably another variable:

$number_correct = 2

Meaning at least two questions answered correctly.

I’ll start digging around in the code. Unfortunately my PHP skills are weak but this will be a good chance to change that.

**Comment by coudot** [comment]
You can start the feature by just managing several answers in the directory:
* Possibility to register several answers from setquestions.php : when user register an answer, it adds it to current answer (or replace the answer if it was already registered)
* The code in resetbyquestions.php is compatible with multiple answers, as it searchs with `{key}value`

The next step will be to require 2 or more answers to reset the password, but this is not required as first implementation.

Please submit a pull request with your code, I will then look at it and help you

**Comment by shawnmckinney** [comment]
> On May 10, 2019, at 2:20 AM, Clément OUDOT <notifications@github.com> wrote:
> 
> Please submit a pull request with your code, I will then look at it and help you

Hello Clement, I have created the pull request.  Please review the code and tell me what you think.

Thanks
—Shawn

**Comment by coudot** [comment]
So for the record, see #303 and #318 for the support of multiple answers
