### ISSUE TITLE
Security assessment issues

### ISSUE THREAD

**Issue by trapangle** [ltb-project/self-service-password#187]
When running an [acunetix test](https://www.acunetix.com/) on self-service-password installed in our infrastructure, a few medium alerts are found : 
* **HTML form without CSRF protection** for the main form (POST login, oldpassword, newpassword, confirmpassword).
* **Development configuration file** : .travis.yml shouldn't be in a publication version (maybe it should just get deleted after installation).
* **User credentials are sent in clear text** : the POST request containing the passwords should be sent only in HTTPS.
* **Vulnerable Javascript library** for js/jquery-1.10.2.min.js, it should be upgraded to a newer version.
* **Password type input with auto-complete enabled**, the password can be stored in the browser cache and an attacker can get it from there. Therefor, auto-complete should be disabled.
* **Documentation file** : README.md shouldn't be in a publication version (maybe it should just get deleted after installation).

**Comment by plewin** [comment]
Thank you for these feedbacks,

> HTML form without CSRF protection for the main form (POST login, oldpassword, newpassword, confirmpassword).

This is true but it is not a big threat as all actions require a valid password & there is no user login/logout. An attacker cannot do much of it.
 
Note: 2.0 proposal has csrf protection implemented

>  Development configuration file : .travis.yml shouldn't be in a publication version (maybe it should just get deleted after installation).

It is not a problem and there is no .travis.yml in releases packages.

> User credentials are sent in clear text : the POST request containing the passwords should be sent only in HTTPS.

Please use tls in all non testing environment.

Note for 2.0 proposal: I plan to make SSP not accept insecure http requests unless a flag allow_insecure_http_transport = true, false by default. I would also like to add a flag accept only tls because IIRC SSL should be considered secure. Unfortunately it's not possible to detect if the request was ssl or tls without a configuration in apache and it is not present by default because of a performance penalty.

> Vulnerable Javascript library for js/jquery-1.10.2.min.js, it should be upgraded to a newer version.

SSP is not affected.

> Password type input with auto-complete enabled, the password can be stored in the browser cache and an attacker can get it from there. Therefor, auto-complete should be disabled.

No, (modern) browsers do not care about the attribute autocomplete for passwords.
Even if you had autocomplete=off it would have no effects. Browsers just ignore it. To be 100% sure it will not be saved by the browser, a dirty hack is needed.

Autocomplete for passwords (and browsers password managers) was controversial but is now generally accepted has good practice.
I like this article for a summary of the situation.
https://www.astechconsulting.com/blog/autocomplete-and-password-security

Note: 2.0 proposal has autocomplete by default.

> Documentation file : README.md shouldn't be in a publication version (maybe it should just get deleted after installation).

Hum. It is not in the deb or rpm, but it is in the tar.gz. I guess it is okay the way it is.

**Comment by trapangle** [comment]
> > Vulnerable Javascript library for js/jquery-1.10.2.min.js, it should be upgraded to a newer version.
>
> SSP is not affected.

Can you explain what you mean ? This version of jQuery is included in SSP : https://github.com/ltb-project/self-service-password/blob/master/js/jquery-1.10.2.min.js

**Comment by plewin** [comment]
jQuery in SSP is almost not used. Today it is only used for the popover help messages of the menu.
The lines of js in SSP do not use vulnerable jquery code (and also do not depend on user submitted data). so SSP is not vulnerable because of jquery. 

On second thoughts we should still upgrade, it is possible that an user forks the code to make a custom theme for ssp using the jquery version provided and a vulnerable jquery code, it is very unlikely IMO but possible.

**Comment by coudot** [comment]
@plewin Are we agree we just need to upgrade jQuery to close this issue?

**Comment by plewin** [comment]
@coudot yes

**Comment by coudot** [comment]
Done
