### ISSUE TITLE
password expires quickly when useing email to reset on RHEL IDM.

### ISSUE THREAD

**Issue by tstefan** [ltb-project/self-service-password#222]
we are a Red Hat shop running IDM,  when we reset our passwords with the link provided in a email. the expire time on the new password is set to expire quickly (about 4 hours) but if we use the self-service password where we proved the old and new password then the password expire date is set to 90 days.

is there a setting somewhere that we are missing that would cause this type of issue?

Thanks

**Comment by pcurie** [comment]
Hi @tstefan 

I can reproduce the issue here, it seems to be linked to IDM default policy : https://www.freeipa.org/page/New_Passwords_Expired

Changing $who_change_password from user to manager and I have the same problem when using the standard procedure with old password.

It seems that this is required if the password change is not done by self.

Looking if you can change that in IDM but it doesn't seems trivial or recommanded.

Kind regards
