### ISSUE TITLE
Reset Password stored in LDAP as plaintext

### ISSUE THREAD

**Issue by anwoke8204** [ltb-project/self-service-password#223]
Hello, I am having an issue where after a user resets a password, the password is stored in plaintext in LDAP.  how can I get this to encrypt the password instead of storing it in plaintext?

**Comment by fbartels** [comment]
This can be configured in the config.inc.php. please see https://github.com/ltb-project/self-service-password/blob/master/conf/config.inc.php#L73-L82

**Comment by anwoke8204** [comment]
I know my issue.  I had it typed in wrong, thats why it wasn't encrypting.

**Comment by fbartels** [comment]
In any case I am wondering if from a security standpoint "clear" should really be the default option here. "auto" seems to be a much better choice (but also relatively new I did not see it before).

**Comment by plewin** [comment]
clear is the default because it is the best practice.
SSP should sent the password in plaintext and the server will perform
additional policy check on it. If SSP is doing the hashing the server can't
verify if the password complies with the policy (for example if it was
already used or is long enough)

Of course ldaps should be used if the password is transmitted in clear.

Auto hash in SSP should really not be used, it tries to detect and reuse
the old hashing method of the previous password.

**Comment by fbartels** [comment]
> Of course ldaps should be used if the password is transmitted in clear.

but even then this setting could lead to the password being stored as clear text in ldap, if the admin did not do any special configuration (like you suggested).

I am not entirely sure how this is handled in a vanilla openldap or ActiveDirectory, but afaik Univention stores the hashes of old passwords in an extra attribute and performs checks like "hey you use this password before" based on this.
