### ISSUE TITLE
LDAP - Modify password error 19 (Constraint violation)

### ISSUE THREAD

**Issue by diogonunes2811** [ltb-project/self-service-password#231]
Hello, good morning. How are you!?

I am new to using the tool, I am trying to configure it but when I try to perform the password change this error is issued LDAP - Modify password error 19 (Constraint violation).

My current setting is samba4 + ad-dc, not debian debian stretch.
Follow my config.inc.php

Thanks for the help and I apologize for using the language because I use google translator.

[config.inc.zip](https://github.com/ltb-project/self-service-password/files/2251048/config.inc.zip)

any tips?

**Comment by plewin** [comment]
Hi,

Constraint violation means that the ldap server understood the request but refused to accept it because it does not comply with its policies.
You will need to check your ldap server logs to understand why it rejected it. If it because because of basic checks like password not long enough, you should configure a similar policy in the config.inc.php of ssp so ssp can tell the user what's wrong with the new password before asking the ldap server to save it. 
You should try with more complex and previously unused passwords to see if it works better.

**Comment by diogonunes2811** [comment]
Ok Thanks for the help, I'll try and return!

**Comment by diogonunes2811** [comment]
I returned ;)

Thank you very much, it really was the samba4 password security parameters, I resealed all of them = 0 tested and it worked !!! Now I will adapt as I need.

Thanks for the quick help, fantastic application!
