### ISSUE TITLE
PHPMailer  Deprecated on php 7.2

### ISSUE THREAD

**Issue by ainuoyan** [ltb-project/self-service-password#253]
Deprecated: __autoload() is deprecated, use spl_autoload_register() instead in /www/wwwroot/safe_dilatoit_com/lib/vendor/PHPMailer/PHPMailerAutoload.php on line 45

**Comment by coudot** [comment]
Doc : http://php.net/manual/en/function.spl-autoload-register.php

**Comment by ainuoyan** [comment]
thank you

**Comment by faust64** [comment]
Hi,

That sounds kind of weird. If I understand properly, you reached a line of the code, that is in the `else` block, of some `if (version_compare(PHP_VERSION, '5.1.2', '>='))`.

This would suggest your PHP version is below 5.1.2.
Thus, there's no reason you would get that warning ...

Is this setup still active?
Any chance you could add some log for your `PHP_VERSION`?

Thanks.

**Comment by JorisVanEijden** [comment]
This is due to the way the PHP code is compiled.
The function is created at compile-time and the version check is done at run-time.
So the version check has no effect on the creation of the `__autoload` function, and the deprecation warning will always be thrown at compile-time. After that the code is cached in the opcache so you won't see the warning again until that expires.

**Comment by coudot** [comment]
PHPMailer was update for 1.4 release, see #439
