### ISSUE TITLE
Login or password incorrect - samba4 active directory

### ISSUE THREAD

**Issue by chrsch** [ltb-project/self-service-password#254]
Hi all, I can't get to change the password because it seems the users fail to authenticate. Basically the connection seems to work (I get user not found error if user not exists). Do I miss something? This is a samba4 active directory with vanilla settings.

Error msg:
```Wed Nov 14 14:06:36.659374 2018] [php7:notice] [pid 1418] [client 172.17.0.1:45148] LDAP - Bind user error 49  (Invalid credentials), referer: http://localhost:8888/index.php```

```<?php
// Override config.inc.php parameters below
$lang = "de";
$debug = true;
$keyphrase = "5xxxxx";
$ad_mode = true;

$ldap_url = "ldaps://xxxxx.de:636";
$ldap_binddn = "CN=xxxxx,CN=Users,DC=anaesthesie-owl,DC=de";
$ldap_bindpw = "xxxxx";
$ldap_base = "dc=xxxxx,dc=de";

$who_change_password = "manager";
$ldap_login_attribute = "mail";
$ldap_fullname_attribute = "cn";
$ldap_filter = "(&(objectClass=person)(mail={login}))";
?>```

**Comment by coudot** [comment]
The error message means the password submitted by the user is incorrect

**Comment by bradjtrammell** [comment]
I am getting the same error, and I KNOW the credentials credentials are valid because 5 other applications are using the exact same credentials, and I'm getting the exact same error message from my setup. My configuration almost exactly matches that of above. If it is indeed the correct configuration, this should work. It appears to be something with the software.

**Comment by bradjtrammell** [comment]
I am getting the same error, and I KNOW the credentials credentials are valid because 5 other applications are using the exact same credentials, and I'm getting the exact same error message from my setup. My configuration almost exactly matches that of above. If it is indeed the correct configuration, this should work.
