### ISSUE TITLE
Question: how is $who_change_password supposed to work?

### ISSUE THREAD

**Issue by cicob** [ltb-project/self-service-password#271]
Hi,
Based on the code I am struggling to understand how the usecase "Manager is changing the password" could ever work. Can someone please add proper documentation, so that it is clear how this feature works?

Change:
If I set this parameter to TRUE, shall I enter the desired userID where the password-change is needed, but the current password from the manager?

Sendtoken: 
Does this form cover the manager-usecase? If so, how excatly. Or is the manager-setting only intended for the CHANGE-feature above?

**Comment by coudot** [comment]
When a user changes its password, SSP will search the user account in the directory and then modify the password.

The password modification can be done either with user account, either with manager account. Of course, to be able to do it with user account, you need to bind as user, so you must have the user password. That's why you can have the choice when changing the password, as you have the user old password. When using password reset, you can't login as user, so the modification is always done as manager.

**Comment by cicob** [comment]
So it seems manager can only use password-reset = change. OK.
This is where I wonder how this usecase works. If the manager is "resetting" the password, what credentials go where in the web-form? 

- Login: employee-id?
- Old password: employee-pw?
- New password: employee-pw? 
- Confirm:  new employee-pw?

Where in this do you enter the credentials of the manager?

![Screenshot](http://ltb-project.org/wiki/_media/documentation/self-service-password/1.0/ssp_1_0_change_password.png?w=800&h=666&tok=abc22c)

**Comment by coudot** [comment]
The manager account is set in configuration:
```php
$ldap_binddn = "cn=manager,dc=example,dc=com";
$ldap_bindpw = "secret";
```

In SSP screen, you always enter user login and password.

**Comment by JuJuMDX** [comment]
Answered by @coudot

**Comment by TheAshwanik** [comment]
> The manager account is set in configuration:
> 
> ```
> $ldap_binddn = "cn=manager,dc=example,dc=com";
> $ldap_bindpw = "secret";
> ```
> 
> In SSP screen, you always enter user login and password.

Hi, @coudot , 
I have just started using SSP, and is considering for use at work. So lot of doubts arising, and checking old issues are helping, but opening questions also at time. Thank you.

it Is this a secure practice to have admin/manager password in configuration file?
Asking from audit perspective.
