### ISSUE TITLE
Self service password unable to change users' passwords

### ISSUE THREAD

**Issue by codesmaker** [ltb-project/self-service-password#304]
Hi,

I've installed Self service password on Debian 9. ppolicy is activated in my LDAP. When I try to change a user's password, I get the following error in the LDAP:
`Must supply old password to be changed as well as new one`

Please note that Self service password is setup so users change their passwords, not "manager"
`$who_change_password = "user";`

This is my ppolicy settings:
dn: cn=default,ou=policies,dc=example,dc=com
objectClass: pwdpolicy
objectClass: person
objectClass: top
cn: default
sn: passwordDefault
pwdAttribute: userPassword
pwdCheckQuality: 0
pwdMinAge: 0
pwdInHistory: 10
pwdMaxFailure: 10
pwdFailureCountInterval: 0
pwdLockout: TRUE
pwdLockoutDuration: 0
pwdSafeModify: TRUE
pwdGraceAuthNLimit: 5
pwdAllowUserChange: TRUE
pwdMustChange: TRUE

Any idea why I'm getting this error?

**Comment by coudot** [comment]
Set pwdSafeModify to FALSE in your LDAP ppolicy.

**Comment by codesmaker** [comment]
Thanks. It worked.

I noticed that users can re-use old passwords. The ppolicy above specifies that the last 10 passwords can't be used. Is that normal?

**Comment by codesmaker** [comment]
Got it. It seems that when "$hash" is set to anything but clear, password history isn't respected. So I set it back to
`$hash = "clear";`

Thanks a lot for the support.

**Comment by nawarhalabi** [comment]
> Set pwdSafeModify to FALSE in your LDAP ppolicy.
Is this a security risk?

**Comment by coudot** [comment]
Not really, depends which application can modify password in your LDAP directory. If only SSP can, this is ok.

**Comment by AGI-chandler** [comment]
> Set pwdSafeModify to FALSE in your LDAP ppolicy.

I don't understand why this change is needed when SSP is asking for the current/old password in the form.  Why doesn't SSP send the current password with the new password?

If the current/old password isn't required then anyone can type in anyone's username and reset their password, that doesn't make sense.  It's pretty standard to require the user to be authenticated before they can change their password, so this seems like a major risk.  We also have other places the password can be changed for example in a terminal.  Turning off pwdSafeModify would also turn off the shell asking for the current password, letting anyone strolling by to change someone's password if they left their terminal unattended...

**Comment by coudot** [comment]
1/ When resetting a password, you don't know the previous password. In this case forcing having the old password breaks the feature.

2/ Trough SSP, it is not possible to use the password change feature without providing the old password.

**Comment by AGI-chandler** [comment]
> 1/ When resetting a password, you don't know the previous password. In this case forcing having the old password breaks the feature.

That's why the manager account is specified in the beginning of the config, who isn't subject to the ppolicy.  Plus the reset via question/answer or email doesn't provide a $who_change option for user, of course.

> 2/ Trough SSP, it is not possible to use the password change feature without providing the old password.

This makes no sense.  Currently, it's not possible to change the password <ins>with</ins> providing the old password, so this page doesn't work either way?  If the old password is required then why we need to turn off `pwdSafeModify`?

**Comment by coudot** [comment]
> That's why the manager account is specified in the beginning of the config, who isn't subject to the ppolicy. Plus the reset via question/answer or email doesn't provide a $who_change option for user, of course.

The manager in SSP is the application account in configuration, it may not be the rootdn of the directory and so can be restricted by ppolicy. In this case ppolicy will block any change attempt trough question/answer or email.


> This makes no sense. Currently, it's not possible to change the password with providing the old password, so this page doesn't work either way? If the old password is required then why we need to turn off `pwdSafeModify`?

The old password is only required with the standard password change. It is of course not required when resetting the password by mail or question/answer.

**Comment by AGI-chandler** [comment]
> The manager in SSP is the application account in configuration, it may not be the rootdn of the directory and so can be restricted by ppolicy. In this case ppolicy will block any change attempt trough question/answer or email.

The default setting in the config is implied to be the rootdn in the format of "cn=manager,dc=example,dc=com"

> The old password is only required with the standard password change. It is of course not required when resetting the password by mail or question/answer.

Again, if the password is required, why does the LDAP server complain `Must supply old password to be changed as well as new one`.

**Comment by coudot** [comment]
> The default setting in the config is implied to be the rootdn in the format of "cn=manager,dc=example,dc=com"

It's an example and best practice is to use a service account, not the rootdn.

> Again, if the password is required, why does the LDAP server complain Must supply old password to be changed as well as new one.

Because the code first check the old password with a bind, and then update the new password with a modify (or extended operation password modify).

With AD mode, we pass the old password in the same modification as the new password because it is the only way to update the password in AD. We could indeed do the same thing with any LDAP server.

Feel free to propose a PR with a dedicated configuration parameter if you think this would enhance the product.

**Comment by AGI-chandler** [comment]
What's AD mode?  Active Directory?  If it's already being done then why not here?  Where are you doing it?  Point me to it.  Of course have more options and working configurations would enhance SSP but i have no specialty in php, or time, but can't use the product either in this current form.

**Comment by AGI-chandler** [comment]
Yes sir I understand, we all do community service in this space, mine with the help of many cups of coffee!
https://ltb-dev.ltb-project.narkive.com/z2EtpYUk/ldap-tool-box-bug-316-new-pwdsafemodify-self-service-password
My goodness though guy, 12 years and it's still an issue, is it that impossible?  I don't know why, I am pretty sure LDAP Account Manager would let us change our passwords but that instance was so old maybe the ppolicy was different too.  My only hope would be try to check the self-service code there, but it won't connect to the old implementation now.  I doubt I would be any help beyond that, but we'll.  It's a shame because I spent much time configuring SSP already.

**Comment by coudot** [comment]
Looking at the archive post, I see that a solution would be to use the exop operation.

Could you try with:
```php
$ldap_use_exop_passwd = true;
$ldap_use_ppolicy_control = false;
```

> 12 years and it's still an issue, is it that impossible?

Nothing is impossible, and it's even better when it is asked with kindness.

**Comment by AGI-chandler** [comment]
I'm not sure how to ask that question with kindness, it was more of a rhetorical observation in amazement of how difficult some things can be and to only discover it after spending so much time on the configuration.  Questions that get to the root of the issue are good too, and the results sure are kind!  You got it Clément!  It works!  I could kiss you! 😜
