### ISSUE TITLE
Configure several LDAP servers and select one depending on context

### ISSUE THREAD

**Issue by soisik** [ltb-project/self-service-password#327]
Hi,

We are setting up a federalized identity management system where users will change their password in their local LDAP server using a federalized SSP. Currently, the only solution would be to install as many SSP instances as we have local LDAP server to change password in, and dispatch users to the right SSP instance when he request a password change. 

For many reasons, we would rather have one SSP instance to deal with, so we are proposing a new feature in SSP configuration management:

- Possibility to dynamically override global and local settings with an extra configuration file, whose reference key is passed in an HTTP_HEADER. Config files would be:
   - config.inc.php
   - config.inc.local.php (if exists)
   - config.inc.%extra-config%.php (if exists)

- HTTP Header name is `SSP-Extra-Config` by default, but can be overridden in config.inc.local.php.

For example, if an incoming request has the HTTP header `SSP-Extra-Config` with the value "mypartner", SSP will load the extra configuration file config.inc.mypartner.php.

PR following.

**Comment by coudot** [comment]
Doc updated: https://ltb-project.org/documentation/self-service-password/1.4/config_general#multi_tenancy

**Comment by jdavis7718** [comment]
I am unable to get this to work as documented and the documentation is a little lacking on it as well.
Here is where I am at with this.

If I name the file config.inc.local.php it is read in and display properly so I know my configuration in the file is correct.
I am attempting to use this with Active Directory so I named a config file config.inc.ad.php
I uncommented the line $header_name_extra_config = "SSP-Extra-Config:";  in config.inc.php to have it listen for that header.
In my apache config I added this line to always send the header equal to value ad
Header always set SSP-Extra-Config "ad"

Per your documentation when it sees the value ad it should read in the config.inc.ad.php file, it does not. 

On a Linux system I used wget to verify the header is added properly, output below
  Server: Apache/2.4.37 (Red Hat Enterprise Linux) OpenSSL/1.1.1g
  X-Powered-By: PHP/7.3.20
  SSP-Extra-Config: ad
  Keep-Alive: timeout=5, max=100
  Connection: Keep-Alive
  Transfer-Encoding: chunked
  Content-Type: text/html; charset=UTF-8

Any help would be much appreciated

**Comment by faust64** [comment]
Hi,

Trying it out: the `Header always set ...` would not work. 
Instead, you should set: `RequestHeader setIfEmpty SSP-Extra-Config "ad"`

Let us know how that goes.

**Comment by jdavis7718** [comment]
Thank you for the quick reply 
That worked. 

In case anyone else runs across this here is my configuration that is working. I would also request that some clarification be adding to the documentation to help avoid any other confusion others may have. 

I left my config.inc.php as default since that is the recommendation to avoid overwrites during upgrades 
I created a config.inc.local.php which contains the following 
<?php 
// Override config.inc.php parameters below 
$header_name_extra_config = "SSP-Extra-Config"; 
?> 

I then created a config.inc.ad.php which has all the customization for my specific 

For the apache configuration file I have added to the virtual host the following line 
RequestHeader setIfEmpty SSP-Extra-Config "ad" 

Thanks for the help and for a great tool
