### ISSUE TITLE
address CVE-2019-11043

### ISSUE THREAD

**Issue by arno01** [ltb-project/self-service-password#350]
The default nginx config seem to be vulnerable to CVE-2019-11043
https://ltb-project.org/documentation/self-service-password/latest/config_nginx

- https://news.ycombinator.com/item?id=21369866
- https://github.com/neex/phuip-fpizdam
- https://www.tenable.com/blog/cve-2019-11043-vulnerability-in-php-fpm-could-lead-to-remote-code-execution-on-nginx

**Comment by maxbes** [comment]
@coudot I was not able to reproduce the exploit on Debian or RHEL, but perhaps that's because the exploit is too specifically tied to a particular configuration.

The longterm solution would be of course to apply PHP security fixes as soon as they become available, but until then, adding 

```
        try_files $fastcgi_script_name =404;
```
to the PHP location block (right below `fastcgi_index` for instance) does not break the application and should circumvent the vulnerability. It's probably a good idea to have this directive anyway.

**Comment by coudot** [comment]
Thanks, documentation updated.
