### ISSUE TITLE
Update jquery to latest, 3.5.1 currently

### ISSUE THREAD

**Issue by ralphsc** [ltb-project/self-service-password#405]
Environment
Python version: 2.7.5
SSP version: v1.3

Proposed Change
Upgrade jquery to the latest release, 3.5.1 currently.

Justification
Currently SSP includes jquery 3.3.1 in the self-service-password/js/ directory.
The vulnerabilities in jquery 3.3.1 can be found here: https://snyk.io/test/npm/jquery/3.3.1

The CVE is:
CVE-2020-11022

**Comment by plewin** [comment]
Thank you for reporting this issue.

For clarification, SSP is not affected by CVE-2020-11022

While SSP includes a library that has new known vulnerabilities, the problematic functions in jquery are not used in the conditions specified by the CVE (because SSP does not use jquery fonctions with data from untrusted sources / user input).

The library still needs to be upgraded to make automatic vulnerability scanners happy.

**Comment by plewin** [comment]
Thanks again for the suggestion @ralphsc 
Next release of SSP will ship a newer jquery.
