### ISSUE TITLE
Can't disable tokens?

### ISSUE THREAD

**Issue by edqallen** [ltb-project/self-service-password#453]
Using the latest version from here with the existing Dockerfile, trying to authenticate against AD.  I've set the following options in the config.inc.local.php file:

```
$debug = true;

$use_recaptcha = false;
$use_tokens = false;
$crypt_tokens = false;
$pwd_min_length = 3;
$pwd_max_length = 1024;

// Bind with the supplied credentials rather than the (anonymous) ones below.
$who_change_password = 'user';

// Special AD handling, different from generic LDAP.
$ad_mode = true;

// AD specific options
$ad_options['force_unlock'] = true; // Force account unlock when password changed.
$ad_options['change_expired_password'] = true; // Allow user to change an expired password.

```

And I've removed the line in the `.dockerignore` file that was preventing this config file from being copied into the container when building.

I am still getting only a "Token encryption requires a random string in keyphrase setting" message when visiting the website.  Searching for this message seemed to indicate the tokens are only used for the email reset method, which I'm not trying to use here, and have tried to disable as above.

**Comment by nodiscc** [comment]
Same issue here on a non-docker installation on apache/php-fpm (from tarball at https://ltb-project.org/archives/ltb-project-self-service-password-1.3.tar.gz) linked to openLDAP .

I have set 

```php
$use_tokens = false;
$crypt_tokens = false;
```

in `conf/config.inc.local.php` but accessing SSP shows the message `Token encryption requires a random string in keyphrase setting`. Nothing is logged even with `$debug = true`. Setting this fixes the problem:

```php
# Encryption, decryption keyphrase, required if $crypt_tokens = true
# Please change it to anything long, random and complicated, you do not have to remember it
# Changing it will also invalidate all previous tokens and SMS codes
$keyphrase = "verylongandrandomphrase";
```

But the `required if $crypt_tokens = true` part of the description seems to be wrong, a non-default keyphrase is always needed.

**Comment by coudot** [comment]
Ok, we'll have a look

**Comment by faust64** [comment]
The condition in index.php mentions `$use_sms` and `$crypt_answers` as well - both default to true, in config.inc.php

```
if ( ( ( $use_tokens and $crypt_tokens ) or $use_sms or $crypt_answers ) and ( empty($keyphrase) or $keyphrase == "secret") )
```

Sounds like an issue with docs, rather than code.

Also, in reaction to editing .dockerignore: sounds like you are shipping config.inc.local.php in your container image. If you want to do so, no one would blame you. Then again, I would assume you have some secrets in there.
Secrets shouldn't ship in rpm packages, as much as they shouldn't in container images.
The config.inc.local is something you should pass to your runtime, using a volume. Then, no one with pull access to your registry may end up with your AD/LDAP credentials.
Docs would eventually mention something like the following: 

```
  docker run -p 80:80 \
        -v /host/path/to/config.php:/var/www/conf/config.inc.local.php \
        -it docker.io/acksyn/self-service-password:latest
```

See https://github.com/ltb-project/self-service-password/pull/469 
Though we should probably publish official self-service-password container images first, instead of my own dockerhub account, ... then fix the docs with proper image URL.

**Comment by alandsidel** [comment]
@coudot Thanks for that and for pointing to the other issue regarding documentation.  I'll try that other option in concert with this one if I go back to using this project.  For now I've switched to using the RDP web access page that comes with windows server to manage this, but I'd rather not run an entire IIS instance just to deal with password changes.

Regarding the config.local.php, there is no security issue with what I'm doing, but thanks for the concern.  I only mentioned it because I didn't want someone suggesting that my problem stemmed from the config.local.php file simply not being copied.  I cannot use volumes or any of that the way you suggest, as our docker cluster is managed by an orchestrator in a load balanced fashion without persistent storage available except through some dodgy hacks.  When this is going to be deployed to production, I'll hack up the config.local.php to pull the credentials in from environment vars, and set those in the deployment instructions for the cluster, as is normal for this kind of thing in enterprise docker installs.

**Comment by edqallen** [comment]
@coudot Thanks for that and for pointing to the other issue regarding documentation.  I'll try that other option in concert with this one if I go back to using this project.  For now I've switched to using the RDP web access page that comes with windows server to manage this, but I'd rather not run an entire IIS instance just to deal with password changes.

Regarding the config.local.php, there is no security issue with what I'm doing, but thanks for the concern.  I only mentioned it because I didn't want someone suggesting that my problem stemmed from the config.local.php file simply not being copied.  I cannot use volumes or any of that the way you suggest, as our docker cluster is managed by an orchestrator in a load balanced fashion without persistent storage available except through some dodgy hacks.  When this is going to be deployed to production, I'll hack up the config.local.php to pull the credentials in from environment vars, and set those in the deployment instructions for the cluster, as is normal for this kind of thing in enterprise docker installs.

(wrong account last post, oops!)

**Comment by coudot** [comment]
Thanks to @faust64 !
