### ISSUE TITLE
Using Multi-tenant allow custom titles

### ISSUE THREAD

**Issue by jdavis7718** [ltb-project/self-service-password#518]
I am using multi-tenant configuration which is working by puling a different config file based on the http header sent.   What I want now is the ability to customize the title at the top of the page.  It appears this is set via the $messages['title'] paramenter in the lang file, I'm using en.inc.php.  If I change the title there it reflects on both tenants.   If I attempt to set the variable $messages['title']  in each tentant config file to attempt to override the lang file it seems to be ignored.  Is there a method for updating the title to be unique per tenant?   
I also should note that I have menus disabled so it is showing this default application name.
Thanks

**Comment by faust64** [comment]
The `lang/xx.inc.php` is being loaded in `htdocs/index.php` ( https://github.com/Worteks/self-service-password/blob/master/htdocs/index.php#L51 ), after the `config/config.inc.php` file ( https://github.com/Worteks/self-service-password/blob/master/htdocs/index.php#L11 ).
The messages array is initialized later: https://github.com/Worteks/self-service-password/blob/master/htdocs/index.php#L274

So, no, as it is, you would not be able to define messages.
While we can't load locales before the configuration, that defines which language to use.

One way we could try would be to create a a "custom" language file, for each tenant that needs customization.
In the `./lang` subfolder, create something like `my-tenant-en.inc.php` (assuming the main language to be english)

```
$ cat <<EOF >./lang/my-tenant-en.inc.php
<?php
require_once('../lang/en.inc.php');
\$messages['title'] = 'title for my tenant';
EOF
```

And then, in your tenant configuration file, instead of setting `$lang = 'en';`, try to load your custom lang instead: `$lang = 'my-tenant-en';`.

It should/might work, ... let us know how that goes.

**Comment by jdavis7718** [comment]
Thanks for the suggestion, but it didn't work. 
There was no change after doing as you suggsted. 
I did try commented out the $message in the original en.inc.php file, after doing that it did pull in the customization, but it applied it to both tenants, which was the same issue I had before. It seems the title is more global and not tenant specific 
Thanks

**Comment by faust64** [comment]
Allright, indeed, the language detection uses locales sent by your browser, and tries matching the first part (`en`), which could lead to the same translations being loaded every time, ...

To fix this, we'll define langs, using the language as a prefix, and your custom site id as the latter part:

```
$ cat custom-en.inc.php 
<?php
require_once('../lang/en.inc.php');
$messages['title'] = "CUSTOM Self service password";

$ cat default-en.inc.php 
<?php
require_once('../lang/en.inc.php');
$messages['title'] = "DEFAULT Self service password";

$ 
```

Next, create the configuration files for your sites:

```
$ cat config.inc.local.php 
<?php
$allowed_lang = array('en-default', 'en-custom'); #make sure language detection won't go over default langs
$keyphrase = "mysecrettoken";
$header_name_extra_config = "SSP-Extra-Config";

$ cat config.inc.default.php 
<?php
$lang = "en-default";

$ cat config.inc.custom.php 
<?php
$lang = "en-custom";
# ^ which could actually look for $header_name_extra_config header value ...

$ 
```

Confirm that depending on which header is passed, you're getting a different response:

```
root@3a7798d29bc0:/var/www/html# curl --header 'SSP-Extra-Config: custom' http://localhost/ 2>/dev/null|grep title
    <title>CUSTOM Self service password</title>
root@3a7798d29bc0:/var/www/html# curl --header 'SSP-Extra-Config: default' http://localhost/ 2>/dev/null|grep title
    <title>DEFAULT Self service password</title>
root@3a7798d29bc0:/var/www/html# curl http://localhost/ 2>/dev/null|grep title
    <title>Self service password</title>
```

**Comment by coudot** [comment]
Another solution is to add some logic in the custom lang file to change message depending on the header value.

In `conf/en.inc.php`, try something like:

```php
$extraConfigKey = "HTTP_".strtoupper(str_replace('-','_',$header_name_extra_config));
$extraConfig = preg_replace("/[^a-zA-Z0-9-_]+/", "", filter_var($_SERVER[$extraConfigKey], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_HIGH));

if ($extraConfig === "custom") {
    $messages['title'] = "CUSTOM Self service password";
} elseif ( $extraConfig === "default") {
    $messages['title'] = "DEFAULT Self service password";
}
```

**Comment by coudot** [comment]
Thanks for the feedback
