### ISSUE TITLE
Formatting of messages

### ISSUE THREAD

**Issue by jdavis7718** [ltb-project/self-service-password#519]
Is there a method for introducing a new line in a message variable, such as $messages['changehelpextramessage']

I have attempted to use \n inside the "" but it doesn't affect the display.
Also is there a method for adding a URL, such as for the end user to click to go to a support portal to file a ticket?
Thanks

**Comment by faust64** [comment]
Hi,

Have you tried adding a `<br/>`?

**Comment by jdavis7718** [comment]
Thanks for the suggestion <br/> seems to just interrupt as text and displays on the page

**Comment by coudot** [comment]
We indeed use Smarty filters to avoid injection. We could authorize HTML in message values but we must forbid them in other variables.

**Comment by jakob42** [comment]
I've just upgrade from 1.3 and face a similar problem. I was pointing my users to our documentation page regarding passwords. That doesn't work anymore, since my <a>-Tag gets shown instead of interpreted. IMHO there should be a way to add HTML (or at least basic HTML, without <script> and the likes). With access to the config file and usually the code itself, I could do much worse then have some HTML shown.

I would be grateful if you would consider making this at least optional.
