### ISSUE TITLE
The token cannot be sent to a different mail address than that in LDAP mailattribute field

### ISSUE THREAD

**Issue by ShoJinto** [ltb-project/self-service-password#535]
In `config.inc.php`  file: `$mail_address_use_ldap = false;`  It means that you can use mailaddress different from LDAP mail. But in practice, it has returned:`Login or password incorrect` . in php-fpm error log I see : `[21-May-2021 14:16:29 Asia/Shanghai] Mail jim@admin.com does not match for user tom`  . What is your logic?
I modified the code of  `sendtoken.php` between 148 and 160 rows, so that the sendtoken process can be successfully executed.
`    if (!$match) {
        if (!$mail_address_use_ldap && $userdn) {
            $match = true; // 放开如果mail_address_use_ldap=false 邮箱地址与ldap中不一致将拒绝发送的限制
        } else {
            if (!$mail_address_use_ldap) {
                $result = "mailnomatch";
                error_log("Mail $mail does not match for user $login");
            } else {
                $result = "mailnomatch";
                error_log("Mail not found for user $login");
            }
        }
    }`
I want to know if it is in line with the logic of your software.

TKS :

**Comment by faust64** [comment]
As far as I understand, while the `$mail_address_use_ldap` avoids having to request users for their e-mail address, setting it to false doesn't allow you to request passwords being reset from just any email address.

Instead of picking the first email address found for that user account, turning `$mail_address_use_ldap` off would have end-user submit his address, while self-service-password would check it against existing `$mail_attribute`. If no match were found, then passwords won't be reset.

Allowing passwords reset without checking the requesting user email at all sounds risky.

**Comment by ShoJinto** [comment]
OK, thank you for your answer. For my own situation, I still intend to continue to use my modified code。

**Comment by ShoJinto** [comment]
tks for your answer. I was understood .

Samuel ***@***.***> 于2021年5月21日周五 下午3:42写道：
