### ISSUE TITLE
show_menu = false displays an empty UL

### ISSUE THREAD

**Issue by maxxer** [ltb-project/self-service-password#563]
Default setup, set `$show_menu = false`. The help message will show an empty list 

![screenshot-login it-2021 06 30-16_49_16](https://user-images.githubusercontent.com/240201/123982368-41c1c480-d9c3-11eb-8e1c-0c22e5dc5852.png)

**Comment by jakob42** [comment]
Yeah, I cannot `$use_tokens = true;` together with `$show_menu = false;` anymore since the link isn't shown. Additionally it shows `$messages['changehelpextramessage']` twice.

![Screenshot 2021-10-05 at 11-44-33 Self service password](https://user-images.githubusercontent.com/82335/136000430-7554c6dd-007c-40f2-a4ba-cb6eb8320e48.png)

**Comment by jakob42** [comment]
Sorry, probably not clear enough: The double changehelpextramessage is fine now, but the link to the email reset still isn't shown, only the empty list element.
