### ISSUE TITLE
Undefined Index Errors

### ISSUE THREAD

**Issue by boothieboy2** [ltb-project/self-service-password#570]
I am seeing these errors constantly as I navigate the site.  Can I get feedback to what these are indicating?

[Tue Aug 10 07:10:52.170815 2021] [php7:notice] [pid 101597] [client 10.90.2.186:58419] PHP Notice:  Undefined index: msg_passwordchangedextramessage in /var/www/id-mgmt/templates_c/9ba4398fe6313a69c351d206d53eb5c904c4d49a_2.file.change.tpl.php on line 139, referer: http://password.intra.techgeeks.org/index.php
[Tue Aug 10 07:10:52.170873 2021] [php7:notice] [pid 101597] [client 10.90.2.186:58419] PHP Notice:  Trying to get property 'value' of non-object in /var/www/id-mgmt/templates_c/9ba4398fe6313a69c351d206d53eb5c904c4d49a_2.file.change.tpl.php on line 139, referer: http://password.intra.techgeeks.org/index.php
[Tue Aug 10 07:10:58.676510 2021] [php7:notice] [pid 101598] [client 10.90.2.186:59480] PHP Notice:  Undefined index: extended_error_msg in /var/www/id-mgmt/templates_c/ed62d40a6f529d9d44c5e9c095ae1838785e0df2_2.file.index.tpl.php on line 68, referer: http://password.intra.techgeeks.org/index.php
[Tue Aug 10 07:10:58.676582 2021] [php7:notice] [pid 101598] [client 10.90.2.186:59480] PHP Notice:  Trying to get property 'value' of non-object in /var/www/id-mgmt/templates_c/ed62d40a6f529d9d44c5e9c095ae1838785e0df2_2.file.index.tpl.php on line 68, referer: http://password.intra.techgeeks.org/index.php

System is Ubuntu 20.04 with Apache2 and PHP 7.4.  Mode is AD.

**Comment by faust64** [comment]
The `msg_passwordchangedextramessage` is related to an optional message, that is not defined by default.
I'm not sure I understand what's going on with the second error.
The `extended_error_msg` is probably due to that variable not being defined - not used on all pages.
Both of which could be fixed initializing corresponding variables ...

The third and fourth one I'm not sure.
Have you checked smarty compiled files (those in `/xxx/templates_c/yyy`)? What code is this referring to exactly?

Leaving aside the first and third log:

- Are you doing anything special?
- Are you experiencing with any issue?
