### ISSUE TITLE
Errors when Using Captchas with Password Reset Emails

### ISSUE THREAD

**Issue by tropf** [ltb-project/self-service-password#602]
Dear maintainer,

thank you for creating and publishing this self service portal. It saved me from setting up a much more heavyweight solution.
My local setup produced a bug in the latest version (1.4.3) that I'd like to report:

## Description
When enabling captchas **and** password reset emails (`$use_token = true`),
the reset email is properly sent **but** errors occur:

```
Warning: ini_set(): A session is active. You cannot change the session module's ini settings at this time in /var/www/self-service-password/htdocs/sendtoken.php on line 174

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /var/www/self-service-password/htdocs/sendtoken.php on line 175

Warning: session_name(): Cannot change session name when session is active in /var/www/self-service-password/htdocs/sendtoken.php on line 177
```

## Steps to reproduce
1. Setup "LDAP Tool Box Self Service Password" and connect it to a working ldap database
2. Make sure errors are printed to the web page (!)
3. Request a password reset link through the web interface for an existing user with a correct email address

## Expected Behavior
The email is sent and no errors are displayed.

## Actual Behavior
The email is sent and the link in it works, but the errors copy-pasted above are printed and visible on the web page.

## Notes
(I haven't written PHP for more than five years, so take this with a grain of salt.)

- Checking the captcha invokes `session_start()` (in the same file).
- This checking happens **before** the token is generated, which calls `session_name("token")` which throws the error because a already started session can't be renamed.
- Note that this call to `session_name()` fails, but the reset functionality is still available. (Does this introduce a security risk?)

**Comment by faust64** [comment]
Hi,

See #603 for a possible fix / to test.
The session_name warning shouldn't be an issue: we would use the session ID, submitted in the confirmation e-mail, to confirm a request is legitimate.
The ini_set use_cookies overrides a default. AFAIU, ensures no cookie would be kept on client side. (https://www.php.net/manual/en/session.configuration.php#ini.session.use-cookies)
The ini_set use_only_cookies should ensure a PHP default wasn't changed: shouldn't be an issue, unless your php.ini says otherwise. AFAIU, ensures client won't be able to assume arbitrary sessions IDs. (https://www.php.net/manual/en/session.configuration.php#ini.session.use-only-cookies)

**Comment by tropf** [comment]
Thank you for the patch.

The errors disappeared, but now the captcha verification does not work anymore.
On over ten tries I always received an error for an incorrect captcha -- somehow the session name seems to interfere with the captcha generation & checking?
