### ISSUE TITLE
 message: send_mail: SMTP connect() failed.

### ISSUE THREAD

**Issue by haodongz** [ltb-project/self-service-password#615]
![image](https://user-images.githubusercontent.com/24855321/147061533-14c92210-b787-4701-8cae-3afc52482a9a.png)

![image](https://user-images.githubusercontent.com/24855321/147055012-f4ca44bc-efcc-4c32-b62b-396a50f071b6.png)

![image](https://user-images.githubusercontent.com/24855321/147053468-1207c0bc-4901-4a69-b87c-3b702b724d6f.png)
![image](https://user-images.githubusercontent.com/24855321/147053542-200ec794-dd07-49e2-8aed-5f3e45c3948b.png)
![image](https://user-images.githubusercontent.com/24855321/147053599-acafaa44-1b7f-4c51-8067-7b38045e2c8a.png)
Hello, I failed to retrieve the password email, and I put the screenshot in the attachment. Take a hard look

**Comment by faust64** [comment]
Error tells about SMTP connection failing.
Checking with `openssl s_client -connect smtp.exmail.qq.com:465`, connection is properly established, certificate is valid.
From the server running self-service-password, can you connect to that SMTP?

If not, it may be some firewall blocking that traffic.
Otherwise, could be worth changing your configuration, setting `smtp_debug = true`, see what we can find in the logs then ...

Is this running from a Docker container? If not: installed from RPM, deb, or git directly? Which version are you running?

**Comment by haodongz** [comment]
![image](https://user-images.githubusercontent.com/24855321/147178439-8667bedd-ddc0-4ec2-b830-c82e92e7cafb.png)
  docker  mage: tiredofit/self-service-password:5.1.2

**Comment by haodongz** [comment]
![image](https://user-images.githubusercontent.com/24855321/147178439-8667bedd-ddc0-4ec2-b830-c82e92e7cafb.png)
  docker  mage: tiredofit/self-service-password:5.1.2

**Comment by faust64** [comment]
Ths `getaddrinfo` error suggests that PHP can't resolve the IP address for this DNS name.
Check the DNS resolver configuration in your container (`/etc/resolv.conf`).

**Comment by haodongz** [comment]
![image](https://user-images.githubusercontent.com/24855321/147217355-ec7b57eb-8efd-41e0-bd5a-6bb44268c4ed.png)

**Comment by faust64** [comment]
Is this your container?
100.100 addresses are part of the ` 100.64.0.0/10` range, which is private.
Can you resolve smtp.exmail.qq.com?

**Comment by haodongz** [comment]
![Uploading image.png…]()
yes

**Comment by haodongz** [comment]
![Uploading image.png…]()
yes

**Comment by haodongz** [comment]
Thank you so much

**Comment by banbushi** [comment]
smtp user is wrong, 
please don't  use xx@xx.com,**### just use  username !**
