### ISSUE TITLE
Improve code factorization

### ISSUE THREAD

**Issue by coudot** [ltb-project/self-service-password#707]
We should at least create lib/ldap.inc.php to define some functions to connect to LDAP and search for an entry

**Comment by artlog** [comment]
this will be part of https://github.com/ltb-project/white-pages/issues/119 current refactoring in #ltb-ldap branch.

**Comment by stevleibelt** [comment]
Because of some special burden, I needed to create some LDAPServer Classes.

How would you like to take on this issue, by providing code/pull requests or by general debating about it?

This this changes, I have to raise the question which php-version the code has to support. Based on the [official support](https://www.php.net/supported-versions.php) page, I would prefer writing code that fits to PHP 8.1.

What do you think? Should this be discussed in a separate issue ticket?

**Comment by coudot** [comment]
> Because of some special burden, I needed to create some LDAPServer Classes.
> 
> How would you like to take on this issue, by providing code/pull requests or by general debating about it?
> 
> This this changes, I have to raise the question which php-version the code has to support. Based on the [official support](https://www.php.net/supported-versions.php) page, I would prefer writing code that fits to PHP 8.1.
> 
> What do you think? Should this be discussed in a separate issue ticket?

Hello @stevleibelt sorry for the late reply.

We will use our common LTB lib: https://github.com/ltb-project/ltb-ldap

**Comment by coudot** [comment]
Need to look at https://github.com/ltb-project/ltb-ldap/pull/7

**Comment by coudot** [comment]
Done in https://github.com/ltb-project/ltb-ldap/pull/12
