### ISSUE TITLE
SMS code won't send when captcha is enabled

### ISSUE THREAD

**Issue by matazar** [ltb-project/self-service-password#720]
After upgrading to version 1.5.1, I've found I can't reset the password using the SMS method when the captcha is enabled.

With the captcha enabled, when you press send on the "Check that user information are correct and press Send to get SMS token" page, it redirects you back to the original SMS page claiming "the captcha is required" with no code sent.

When the captcha is disabled, the code is sent and the user is redirected to the SMS token page after clicking send as expected.

No errors are written to the logs file when this happens.

This is on FreeBSD using nginx with the sms_method set to mail. Tested with both PHP74 and PHP80.

**Comment by coudot** [comment]
May be linked to fix on PHP session management. We need to reproduce and search a solution

**Comment by coudot** [comment]
I reproduce.

Should come from #680

**Comment by artlog** [comment]
working on

**Comment by artlog** [comment]
sendsms.php is called multiple times and the second time (smsuserfound) it is called captcha is not displayed but captcha check is done again.
Before #680 captcha reference remained in session in this particular case, session was not cleared and check did pass since captcha cookie was kept too.
current #680 code consider that once a check is done on captcha can't be rechecked again unless a new captcha is reissued.
sendsms.tpl used in case smsuserfound does not redisplay a captcha but chacking is done.
I have to clarify this captcha checking then.

**Comment by artlog** [comment]
did kept in sendsms same checking place than before #680 but keep new generic function. fix regression and keep feature.

**Comment by artlog** [comment]
@matazar Thanks for the report ! I have to appologize, since i am responsible of this regression.

**Comment by matazar** [comment]
@artlog It's no problem, thank you for addressing it so quickly!
