### ISSUE TITLE
mcrypt is outdated

### ISSUE THREAD

**Issue by dsclassen** [ltb-project/self-service-password#85]
I've found many security people who recommend NOT using libmcrypt. It is aan old and unmaintained package.

https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong

I am running php 7.0.10 on a CentOS7 machine and there is no mcrypt package available. I'm still trying to decide what to do, but in the meantime I thought I'd start a discussion here about potentially removing the mcrypt dependency for your project.

Cheers

**Comment by coudot** [comment]
Indeed, we can use another library, we just need to rewrite encrypt/decrypt functions. Which other library is recommended?

**Comment by plewin** [comment]
@coudot it depends on which php versions are supported.

no library is required for php >= 7.0
under 7.0, recommended extension is libsodium, it is not common. best alternatives are reading /dev/urandom or use mcrypt. openssl is not reliable on all php versions.

I tried to remove mcrypt and unsecure mt_rand for [#59](https://github.com/ltb-project/self-service-password/issues/59) unfortunately SSP use random bytes but also random integers, the code to implement them both ends up close to [random_compat](https://github.com/paragonie/random_compat)

I believe SSP should use random_compat to replace mt_rand and mcrypt. It will work out of the box for php 7 but for php < 7 it may require more work.

SSP can adopt 2 strategies for php < 7 :

- Request the installation of the mcrypt if php < 7.0 In order to be sure that a cryptography fonctions are present.
- Not installing anything and see if random_compat produces an exception at runtime. If an exception occurs, SSP would tell the user to install an extension, libsodium or simply mcrypt.

**Comment by coudot** [comment]
Done by @plewin in PR #92
