### ISSUE TITLE
Error 500 when clicking 'Send' on the password change screen

### ISSUE THREAD

**Issue by tediroca** [ltb-project/self-service-password#914]
I'm using SSP 1.6.0 and the error seems to started happening after upgrading from the previous release. I've also noticed that after the upgrade users were taken to 'ssp.example.com' instead of the correct URL, so had to change the 'reset_url' in my config.inc.local.php.

After clicking on the 'Send' button, the browser returns an error 500 without any additional details. 

I've checked the Apache error log but it's empty. Also tried generating other type of errors to confirm that the log is writtable and worked fine.

The Access log does not show any details other than the error 500:

```
<mi_ip> - - [12/Jun/2024:11:01:41 +0200] "POST / HTTP/1.1" 500 - "https://<hostname>/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
```

'/var/log/httpd/error_log' doesn't contain any other information.

PHP 8.1.29
Rocky Linux 8.9

**Comment by coudot** [comment]
Set $debug to true to have logs

**Comment by tediroca** [comment]
> Set $debug to true to have logs

It's already enabled:

`sh-4.4$ grep 'debug' /etc/self-service-password/config.inc.local.php
$debug = true;`

**Comment by coudot** [comment]
So you should see something in error.log or php-fpm logs, depending on your installation

**Comment by chillje** [comment]
Hi :)
We are facing the same problem in the 1.6 release (1.6.1).
I have already investigated this bug and found a simple solution.

You are using files from another project in `vendor/ltb-project/ldap` (from https://github.com/ltb-project/ltb-common) since the 1.6 release. 
Here you can find a problem in line 268 of file `Ldap.php` (see: https://github.com/ltb-project/ltb-common/blob/c4c8507017859ce06b16974b304d24188d119bd7/src/Ltb/Ldap.php#L268).
`$password_values = \Ltb\PhpLDAP::ldap_get_values($this->ldap, \Ltb\PhpLDAP::ldap_first_entry($this->ldap, $search_userpassword), $pwdattribute);`

At a password change the function `ldap_get_values` from `\Ltb\PhpLDAP` is triggert and than indirectly the `\Ltb\PhpLDAP::ldap_first_entry`. 
In this case it is called `ldap_first_entry` from https://github.com/ltb-project/ltb-common in Line 104 (see: https://github.com/ltb-project/ltb-common/blob/c4c8507017859ce06b16974b304d24188d119bd7/src/Ltb/PhpLDAP.php#L104) which needs 3 attributes but you called it with 2.

I simply changed 
` $password_values = \Ltb\PhpLDAP::ldap_get_values($this->ldap, \Ltb\PhpLDAP::ldap_first_entry($this->ldap, $search_userpassword), $pwdattribute);`
to
`$password_values = \Ltb\PhpLDAP::ldap_get_values($this->ldap, ldap_first_entry($this->ldap, $search_userpassword), $pwdattribute);`
so there is used the function ldap_first_entry like in this project here (see: https://github.com/ltb-project/self-service-password/blob/b742d6b543be5e74474d102f42e0db344a365b9f/lib/functions.inc.php#L404).

Now the password change is working as expected.

@coudot 
Can you have a deeper look in this? I dont want to give a PR for this because of my quick investigation and tests for this. You have way more insights in this code :)

**Comment by davidcoutadeur** [comment]
Thanks for the report. The signature method in PhpLDAP.php is indeed incorrect. Will fix this in next release.
